- pulumi/aws/README.md
- pulumi/aws/logagent/__main__.py
- pulumi/aws/start_all.sh
This update adds some additional logic to the start_all.sh script that is intended to make it 
easier for first-time users. 
1. When selecting a stack, the script will create the stack with the name given if one does not already exist.
2. The script will prompt for and add the AWS profile to the Pulumi configuration files in each project directory.
3. The script will prompt for and add the AWS region to the Puumi configuration files in each project directory.
The readme file has been updated to include this information.
There is one minor fix in this PR; elastic has pulled filebeat 7.13.2 from their repo, so we have reverted to 7.13.1.
> feat: add logic to startup script to set, check, and validate config variables

- pulumi/aws/README.md
- pulumi/aws/config/Pulumi.stackname.yaml.example
- pulumi/aws/kic-image-build/ingress_controller_image.py
- pulumi/aws/kic-image-build/test_build_kic_image.py
- pulumi/aws/kic-pulumi-utils/kic_util/archive_download.py
- pulumi/aws/kic-pulumi-utils/kic_util/test_archive_download.py
- pulumi/aws/kic-pulumi-utils/kic_util/test_url_type.py
- pulumi/aws/kic-pulumi-utils/kic_util/url_type.py
- pulumi/aws/kic-pulumi-utils/setup.py
This change adds support to the kic:src_url configuration parameter for git URLs. Additionally, it changes the behavior of the default operation when src_url is left unspecified to check out the KIC source directly from github using the latest tag instead of downloading a tar.gz archive from github.
> feat: add git url support to kic-image-build

- pulumi/aws/requirements.txt
This change upgrades the pulumi python module dependency because it was being intentionally held back due to a bug. Moreover, it changes the format of version matching such that all dependencies will only install minor version updates.
> chore: bumping dependency versions

- pulumi/aws/README.md
- pulumi/aws/anthos/__main__.py
- pulumi/aws/anthos/cert/self-sign.yaml
- pulumi/aws/certmgr/Pulumi.yaml
- pulumi/aws/certmgr/__main__.py
- pulumi/aws/config/Pulumi.stackname.yaml.example
- pulumi/aws/destroy.sh
- pulumi/aws/start_all.sh
Add TLS support to the bank of anthos application, including an example ingress object using a self-signed cluster issuer resource. This requires adding cert-manager to the project as well. This can be used by additional ingress objects deployed as part of this framework.
This will close #6 
> feat: add tls support with selfsigned certs

- pulumi/aws/README.md
- pulumi/aws/anthos/__main__.py
- pulumi/aws/anthos/config/Pulumi.stackname.yaml.example
- pulumi/aws/config/Pulumi.stackname.yaml.example
- pulumi/aws/start_all.sh
This addresses a bug introduced with #30 - the password is part of the connection string, but pulumi does not decrypt it for use in the string concatenation needed to build it. This has been fixed by using the `Output.unsecret` method.
> fix: decrypt postgres password for use in connection string

- pulumi/aws/certmgr/__main__.py
- pulumi/aws/grafana/__main__.py
- pulumi/aws/kic-helm-chart/__main__.py
- pulumi/aws/logagent/__main__.py
- pulumi/aws/logstore/__main__.py
- pulumi/aws/prometheus/__main__.py
- pulumi/aws/sirius/__main__.py
Currently, MARA uses helm charts within pulumi. This approach works, but has some drawbacks as pulumi is not executing helm directly but instead is using the data in the helm chart to provision resources. The new (as of SDK 3.7+) release approach uses the helm SDK, which provides a great deal more flexibility.
This change cuts all the projects that use helm.chart over to helm.release, and adds some additional logging, error checking, and cleanup around the charts. We now lint the charts before we run them, and we rollback and cleanup any failures.
This has also changed the way we pull the hostname of the ELB; this logic may need to be adjusted for environments where a hostname is not provided and an IP is returned instead.
Testing is still underway; this change may require that we install …
> feat: move to beta pulumi k8 sdk to migrate to helm releases

- pulumi/aws/README.md
- pulumi/aws/destroy.sh
- pulumi/aws/observability/Pulumi.yaml
- pulumi/aws/observability/__main__.py
- pulumi/aws/observability/otel-objects/README.md
- pulumi/aws/observability/otel-objects/otel-collector-full.yaml
- pulumi/aws/observability/otel-objects/otel-collector.yaml
- pulumi/aws/observability/otel-objects/otel-collector.yaml.basic
- pulumi/aws/observability/otel-objects/otel-collector.yaml.basic-debug
- pulumi/aws/observability/otel-objects/otel-collector.yaml.full
- pulumi/aws/observability/otel-objects/otel-collector.yaml.hold
- pulumi/aws/observability/otel-objects/otel-collector.yaml.lightstep
- pulumi/aws/observability/otel-operator/__main__.py
- pulumi/aws/observability/otel-operator/opentelemetry-operator.yaml
- pulumi/aws/sirius/__main__.py
- pulumi/aws/start_all.sh
This is the first step at integrating the observability changes into the project. This deploys the OTEL operator into its own namespace, and then instantiates a collector in the `observability` namespace. 
The configuration for the collector is kept intentionally simple; by default the collector will listen for OTEL traffic on grpc and HTTP, and output that data to the stdout of the container. The output is summarized.
For additional configurations, please see the README in the `observability` directory.
> feat: add otel operator and sample configurations

- bin/start_kube.sh
- docs/getting_started.md
- docs/status-and-issues.md
- pulumi/python/README.md
- pulumi/python/kubernetes/nginx/ingress-controller-repo-only/__main__.py
The original version of the repo-only IC deployment only allowed for NGINX Plus; this version allows for both versions of the NGINX controller - the standard OSS version or the Plus version. Documentation has been updated to reflect this change.
> feat: add ability to deploy NGINX IC or NGINX Plus IC from reg

- bin/destroy.sh
- bin/destroy_do.sh
- bin/start.sh
- bin/start_do.sh
- config/pulumi/Pulumi.stackname.yaml.example
- config/requirements.txt
- docs/getting_started.md
- docs/status-and-issues.md
- pulumi/python/README.md
- pulumi/python/infrastructure/digitalocean/domk8s/Pulumi.yaml
- pulumi/python/infrastructure/digitalocean/domk8s/__main__.py
- pulumi/python/infrastructure/kubeconfig/__main__.py
- pulumi/python/kubernetes/applications/sirius/__main__.py
This change adds support for Digital Ocean, including the ability to stand up and tear down a K8 cluster as well as the additional logic required to deploy the monitoring/management resources and the Bank of Sirius application.
This change only works with the ingress-controller being deployed from the repo (NGINX or NGINX Plus). Full support for building the Ingress Controller, pushing to a private registry, etc will be implemented as part of #81. Full support for the IP/Hostname assigned by the K8 LoadBalancer object will continue to be managed by #82 
> Add DigitalOcean Support

- bin/start_aws.sh
- bin/start_do.sh
- bin/start_kube.sh
- config/pulumi/Pulumi.stackname.yaml.example
- extras/jenkins/AWS/Jenkinsfile
- extras/jenkins/DigitalOcean/Jenkinsfile
- extras/jenkins/K3S/Jenkinsfile
- extras/jenkins/MicroK8s/Jenkinsfile
This change closes #99 by implementing the NO_COLOR variable for our start scripts which will allow the Jenkins output to be a bit cleaner without ANSI color codes.
This also removes the slackSend() calls from the Jenkinsfiles, as this is redundant when the Slack Global plugin is used. 
> feat: support NO_COLOR (#99) update jenkins slack calls

- pulumi/python/kubernetes/nginx/ingress-controller/__main__.py
When image_tag_alias is blank, a custom KIC image is not loaded because image_tag_alias may be present in repository_url but just a blank string. This change consolidates the logic into a single function and adds a check for a blank string.
This PR fixes #117 and updates to the 1.3 tag for the Bank of Sirius app.
> fix(bug): fix #117 handle blank image_tag_alias

- config/pulumi/Pulumi.stackname.yaml.example
- pulumi/python/kubernetes/nginx/ingress-controller/__main__.py
We relied on detecting the string 'plus' at the end of the KIC image tag in order to determine if we would be deploying KIC in Plus-enabled mode. This logic was faulty, and it is best to replace it with an explicit configuration option.
> fix(bug): fix #119 use configuration to enable NGINX Plus

- bin/setup_venv.sh
The architecture check performed by `bin/setup_venv.sh` relies on the output
of the `uname -m` command. On M1 macs running macOS 12.0.1 this returns `arm64`.  This change
adds an explicit handler for that response.
> fix: Allow python setup script to move ahead on `arm4`  architecture

- config/pulumi/Pulumi.stackname.yaml.example
- extras/jenkins/AWS/Jenkinsfile
- extras/jenkins/DigitalOcean/Jenkinsfile
- extras/jenkins/K3S/Jenkinsfile
- extras/jenkins/Linode/Jenkinsfile
- extras/jenkins/MicroK8s/Jenkinsfile
- pulumi/python/infrastructure/digitalocean/domk8s/__main__.py
This PR fixes two additional issues with the Jenkinsfiles that were not allowing them to start on the jenkins managed agents. Additionally, this contains a bump in the K8 version supplied by DigitalOcean. This changes fairly frequently (the DO version slugs) so it may make sense to programmatically pick the latest within a given range in future updates.
> fix: additional updates for Jenkins and updated K8 version for DO

- bin/setup_venv.sh
The feature flag `--use-feature=in-tree-build` was introduced in pip 21.1 and then
the feature was mainlined in pip 21.3.  With the flag in place `pip install` command
fails and `kic_utils` fails to build.
Based on the changelog which states that this behavior is default in pip 21.3+ and the current
build installs pip 22.1 we remove the flag.
fixes #145
Describe the use case and detail of the change. If this PR addresses an issue 
on GitHub, make sure to include a link to that issue here in this description 
(not in the title of the PR).
> fix: pip3 install now does not accept the `--use-feature=in-tree-build`

- extras/jenkins/MicroK8s/Jenkinsfile
This is a work-around for the issue found in #151  - it merely pins the microk8s version to 1.23. We do need to figure out why 1.24 is failing and see if that failure is consistent across all deployments.
This does open up a discussion into the wider issue of versions within MARA.
> fix: pin version of microk8s snap

- bin/setup_venv.sh
`pipenv install` will actually update the `Pipfile.lock` when run if there are newer versions of non-pinned dependences or sub dependencies.  This was causing issues with repeatable installs of python dependencies.
This change changes the `setup_venv.sh` script to use `pipenv sync` which does what you'd expect `install` to do and install strictly from the `Pipenv.lock`.
> bugfix: change pipenv install to pipenv sync to avoid updating deps at build time

- extras/jenkins/AWS/Jenkinsfile
- extras/jenkins/DigitalOcean/Jenkinsfile
- extras/jenkins/K3S/Jenkinsfile
- extras/jenkins/Linode/Jenkinsfile
- extras/jenkins/MicroK8s/Jenkinsfile
- extras/jenkins/Minikube/Jenkinsfile
The mystery of "why the automated jenkins deploys are not cleaning up" has been solved; had an erroneous \ in the find command that caused the execdir command to not be executed. 
> fix: typo in find command was causing pulumi stacks to not be deleted

- extras/jenkins/AWS/Jenkinsfile
- extras/jenkins/DigitalOcean/Jenkinsfile
- extras/jenkins/K3S/Jenkinsfile
- extras/jenkins/Linode/Jenkinsfile
- extras/jenkins/MicroK8s/Jenkinsfile
- extras/jenkins/Minikube/Jenkinsfile
- pulumi/python/Pipfile.lock
This fixes bugs introduced in #160 for the Jenkins runs, and goes through and makes additional changes that are intended to improve readability and maintainability. This includes adding in fully qualified paths for utilities that we are using, rather than relying on the shell's PATH. In some instances this was leading to the wrong binary being used.
> chore: jenkins fixes and general cleanup of jenkinsfiles

- docs/getting_started.md
- docs/status-and-issues.md
- pulumi/python/README.md
> chore: doc updates for automation-api changes

- bin/setup_venv.sh
At some point, the installation of `wheel` as a separate item in the `setup_venv.sh` script was removed. This resulted in an issue on the Apple ARM architecture, as tracked in #186.
This change adds `wheel` back into the setup file, and closes #186.
> fix: add wheel back into setup_venv.sh

- bin/start_kube.sh
This change will bring the start_kube.sh script back inline with the description that is given in 
the blogpost on deployment to MicroK8s. Note that the workstation deployments (as well as
GCP and Azure) do not go through the Automation API and still use these scripts.
The only change is that we now have the autogeneration of passwords in place for script 
launched deployments; the automation API follows it's own path and requires these passwords
to be created.
This code was live before, so it should work. Famous last words.
> fix: add in autopw logic inadvertently removed for kube deploys

- config/pulumi/Pulumi.stackname.yaml.example
- pulumi/python/kubernetes/certmgr/__main__.py
- pulumi/python/kubernetes/logstore/__main__.py
- pulumi/python/kubernetes/nginx/ingress-controller-repo-only/__main__.py
- pulumi/python/kubernetes/nginx/ingress-controller/__main__.py
- pulumi/python/kubernetes/observability/otel-operator/README.md
- pulumi/python/kubernetes/observability/otel-operator/opentelemetry-operator.yaml
- pulumi/python/kubernetes/prometheus/__main__.py
Bumping the versions of our helm charts and our observability operator.
> chore: bump helm and observabiilty versions

- bin/start_kube.sh
- pulumi/python/requirements.txt
This minor change updates where the kubeconfig deployments store the prometheus/grafana password; it is now 
stored in the secrets project, not the main project configuration.
Closes #204 
- [ X I have rebased my branch onto master
> fix: adjust where grafana password is stored for kubeconfig deploys

- config/pulumi/Pulumi.stackname.yaml.example
- extras/jenkins/DigitalOcean/Jenkinsfile
- pulumi/python/automation/main.py
- pulumi/python/automation/providers/do.py
This is a stop-gap measure to help with #208 - if the user has not specified the DIGITALOCEAN_TOKEN we will
warn them that it also needs to be in the environment.
Additional changes will make this a bit neater, but this will address it in the short term.
> fix: update digital ocean token configuration variable and insert warning

- config/pulumi/Pulumi.stackname.yaml.example
- pulumi/python/kubernetes/nginx/ingress-controller-repo-only/__main__.py
- pulumi/python/kubernetes/nginx/ingress-controller/__main__.py
- pulumi/python/utility/kic-image-build/__main__.py
This is a temp fix for #225 - it pins our NGINX Ingress helm chart to 0.15.2 and our NGINX binary to 2.4.2 if no other value exists in the pulumi configuration for that stack. 
This will be reverted once the issues defined in #225 are mitigated. 
> chore: pin to KIC helm 0.15.2 / image 2.4.2 due to #225
