- .github/workflows/pulumi-aws-tests.yml
- pulumi/aws/kic-pulumi-utils/kic_util/pulumi_config.py
- pulumi/aws/kic-pulumi-utils/kic_util/test_pulumi_config.py
- pulumi/aws/test.py
This PR fixes issues with the AWS Pulumi test runner and adds the AWS Pulumi test runner as a github action.
> Add unit test runs as github actions CI

- .github/workflows/pulumi-aws-tests.yml
- pulumi/aws/test.py
> Fix github test actions to work with kic-util module

- pulumi/aws/README.md
- pulumi/aws/config/Pulumi.stackname.yaml.example
- pulumi/aws/eks/__main__.py
- pulumi/aws/kic-image-build/__main__.py
This change allows various parameters for EKS and kic image build to be configurable using config files.
> feat: eks and image build are now configurable

- pulumi/aws/Dockerfile.ubuntu
- pulumi/aws/README.md
- pulumi/aws/anthos/__main__.py
- pulumi/aws/anthos/verify.py
- pulumi/aws/build_dev_docker_image.sh
- pulumi/aws/destroy.sh
- pulumi/aws/docs/getting_started.md
- pulumi/aws/requirements.txt
- pulumi/aws/setup_venv.sh
- pulumi/aws/start_all.sh
This PR improves the getting started documentation and makes many improvements to the start, setup and destroy scripts.
This PR fixes #19
> Various user improvements

- README.md
- docs/status-and-issues.md
- pulumi/python/kubernetes/certmgr/__main__.py
- pulumi/python/kubernetes/logagent/__main__.py
- pulumi/python/kubernetes/logstore/__main__.py
- pulumi/python/kubernetes/nginx/ingress-controller-repo-only/__main__.py
- pulumi/python/kubernetes/nginx/ingress-controller/__main__.py
- pulumi/python/kubernetes/prometheus/__main__.py
- pulumi/python/tools/nfsvolumes/__main__.py
Bug fixes to branch; currently just timeouts.
> fix: config value timeout is an int, we were pulling it as a string

- bin/start_aws.sh
- bin/start_kube.sh
- config/pulumi/Pulumi.stackname.yaml.example
- pulumi/python/kubernetes/prometheus/__main__.py
This change closes two issues:
- Closes #87 
- Closes #94 
> fix: address grafana config (#87) and aws/pulumi issues (#94) 

- README.md
Copyedited newest ReadMe, keeping the more familiar voice than previous drafts.
Basic copyedits on latest ReadMe and will also copyedit newest Pulumi ReadMe.
> Updated copyedits

- pulumi/python/README.md
Light copyedits on Pulumi ReadMe.
> Pulumi README copyedits

- bin/start_aws.sh
- bin/start_do.sh
- bin/start_kube.sh
- extras/jenkins/AWS/Jenkinsfile
- extras/jenkins/DigitalOcean/Jenkinsfile
- extras/jenkins/K3S/Jenkinsfile
- extras/jenkins/MicroK8s/Jenkinsfile
This fix addresses a bug created as part of the addition of the logic to handle NO_COLOR (#107).
> fix: fix for #107 NO_COLOR unbound var

- pulumi/python/requirements.txt
Describe the use case and detail of the change. If this PR addresses an issue 
on GitHub, make sure to include a link to that issue here in this description 
(not in the title of the PR).
> chore: bump setuptools to fix setup_venv.sh failures

- extras/jenkins/AWS/Jenkinsfile
- extras/jenkins/DigitalOcean/Jenkinsfile
- extras/jenkins/K3S/Jenkinsfile
- extras/jenkins/Linode/Jenkinsfile
- extras/jenkins/MicroK8s/Jenkinsfile
Adding the pulumi access token to the Jenkinsfiles for our builds in order to better manage CI with Jenkins.
> feat: add PULUMI_ACCESS_TOKEN to Jenkinsfiles

- docs/status-and-issues.md
- extras/jenkins/AWS/Jenkinsfile
- extras/jenkins/Minikube/Jenkinsfile
Created Jenkinsfile to enable minikube automatic deployment; fixed minor issue in AWS Jenkinsfile.
> feat: add minikube jenkinsfile and test

- bin/start_do.sh
- bin/start_kube.sh
- bin/start_lke.sh
- config/pulumi/Pulumi.stackname.yaml.example
- docs/accessing_mgmt_tools.md
- docs/getting_started.md
- pulumi/python/infrastructure/aws/eks/__main__.py
- pulumi/python/requirements.txt
This change encapsulates some small bespoke changes:
1. AWS EKS version is bumped to 1.22 to be inline with the other cloud deploys.
2. New information is printed at the end of each run of the process in order to help new users understand what to do next (once the installation finishes)
3. Document put in place to explain how to access the MARA Mgmt Tooling.
4. Updates to the Python requirements to latest versions that play nice together and with MARA.
> feat: bump AWS k8 version and add more detailed docs / information for users

- bin/start_aws.sh
- bin/start_do.sh
- bin/start_kube.sh
- bin/start_lke.sh
- extras/jenkins/AWS/Jenkinsfile
- extras/jenkins/DigitalOcean/Jenkinsfile
- extras/jenkins/K3S/Jenkinsfile
- extras/jenkins/Linode/Jenkinsfile
- extras/jenkins/MicroK8s/Jenkinsfile
- extras/jenkins/Minikube/Jenkinsfile
This fix addresses a bug introduced with #129 where the startup script would fail on retrieval of the IP address from kuberentes. This includes using the correct service name and adds in an or condition for cases where we cannot retrieve the address (which could be a symptom of a problem and not a problem itself) so that the operator can debug.
> fix: problems with loadbalancer ip address display #130 password #132

- docs/status-and-issues.md
Small change; this works with the Jenkins CI system to publish the deployment statuses for the pipelines we have configured for testing.
> feat: add deployment badges

- extras/jenkins/AWS/Jenkinsfile
- extras/jenkins/DigitalOcean/Jenkinsfile
- extras/jenkins/K3S/Jenkinsfile
- extras/jenkins/Linode/Jenkinsfile
- extras/jenkins/MicroK8s/Jenkinsfile
- extras/jenkins/Minikube/Jenkinsfile
The existing Jenkins configuration tried to build all the branches from the repo, but this has proven to be a bit problematic for our use case.
This change restricts the build to `*/master` for now - we can look into a reconfig later to make this part of the merge process, but for now this fixes the immediate concern. See #163 for potential concerns moving forward.
> chore: update git to only pull master branch for deployment tests

- config/pulumi/Pulumi.stackname.yaml.example
- pulumi/python/kubernetes/certmgr/__main__.py
- pulumi/python/kubernetes/certmgr/manifests/cert-manager.crds.yaml
- pulumi/python/kubernetes/logagent/__main__.py
- pulumi/python/kubernetes/logstore/__main__.py
- pulumi/python/kubernetes/nginx/ingress-controller/__main__.py
- pulumi/python/kubernetes/observability/otel-objects/otel-collector.yaml
- pulumi/python/kubernetes/observability/otel-operator/opentelemetry-operator.yaml
- pulumi/python/kubernetes/prometheus/__main__.py
This PR adds fixes to the automation-api branch to address issues seen in testing; current testing has been performed on linode, additional testing will take place after merge.
> fix: add in updates to automation-api branch for version bumps

- extras/README.md
added text
Describe the use case and detail of the change. If this PR addresses an issue 
on GitHub, make sure to include a link to that issue here in this description 
(not in the title of the PR).
> text added to readme file

- extras/jenkins/Linode/Jenkinsfile
- pulumi/python/automation/main.py
Missed these on the last PR; two simple changes. One adds comments and adjusts logging for the automation-api, the other fixes two typos in the Jenkinsfile for Linode.
> fix: linode jenkinsfile and log level adjust / comment add

- sumo.md
Describe the use case and detail of the change. If this PR addresses an issue
on GitHub, make sure to include a link to that issue here in this description
(not in the title of the PR).
- [x ] I have written my commit messages in the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) format.
- [ x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [ x] I have added tests (when possible) that prove my fix is effective or that my feature works
- [ x] I have checked that all unit tests pass after adding my changes
- [ x] I have updated necessary documentation
- [ x] I have rebased my branch onto master
- [ x] I will ensure my PR is targeting the master branch and pulling from my branch from …
> corrected a couple of typos in the README
